config/routes.rb
Class6hwforum::Application.routes.draw do

  get "/" => "home#index"

  get "/entry" =>"home#entry", as: :entry

  resources :users do
    resources :topics do
      resources :replies
    end
  end

  get "/topics" => "topics#all"

  get "/sessions/new" => "sessions#new"

  post "/sessions/new" => "sessions#create"

  delete "/sessions" => "sessions#destroy", as: :logout

  get "/search/users" => "users#search", as: :search_users

end

app/models/reply.rb
class Reply < ActiveRecord::Base

	belongs_to :user
	belongs_to :user

end

app/models/topic.rb
class Topic < ActiveRecord::Base

	belongs_to :user
	has_many :replies
	
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :topics
	has_many :replies

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@user = User.find_by_id(session[:user_id])
		if @user
			redirect_to entry_path
		else
			redirect_to sessions_new_path
		end
	end

	def entry

	end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

	def index

	end

	def new
		@reply = Reply.new
		@topic = Topic.find(params[:topic_id])
		@user = User.find(params[:user_id])
	end

	def create
		@reply = Reply.create(reply_params)
		@reply.user_id = params[:user_id]
		@reply.topic_id = params[:topic_id]
		if @reply.save
			redirect_to user_topic_path(@reply.user_id, @reply.topic_id)
		else
			flash[:alert] = "There was a problem posting your reply."
			redirect_to :back
		end
	end

	def edit

	end

	def update

	end

	def destroy
		@author = User.where(id: params[:user_id]).first
		@reply = Reply.where(id: params[:id]).first
		if @reply && @reply.destroy
			flash[:notice] = "Your post was deleted successfully."
			redirect_to user_topic_path(@author.id, @reply.topic_id) 
		else
			flash[:alert] = "There was a problem deleting your post."
			redirect_to :back
		end
	end

private
	
	def reply_params
		params.require(:reply).permit(:body)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		@user = User.where(email: params[:email]).first
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			flash[:notice] = "Welcome #{@user.fname}!"
			redirect_to entry_path
		else
			flash[:alert] = "There was a problem logging you in."
			redirect_to sessions_new_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have been logged out sucessfully."
		redirect_to sessions_new_path
	end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	def all
		@topics = Topic.all
	end

	def index
		@user =	User.find(params[:user_id])
		@topic = Topic.new
	end

	def show
		@topic = Topic.find(params[:id])
		@user = User.find(session[:user_id])
		@reply = Reply.new
	end

	def new
		@topic = Topic.new
		@user = User.find(params[:user_id])
	end

	def create
		@topic = Topic.create(topic_params)
		@topic.user_id = params[:user_id]
		if @topic.save

			redirect_to user_topic_path(@topic.user, @topic.id)
		else
			flash[:alert] = "There was a problem submitting your post."
			redirect_to :back
		end
	end

	def edit

	end

	def update

	end

	def destroy
		@topic = Topic.where(id: params[:id]).first
		if @topic && @topic.destroy
			flash[:notice] = "Your post was deleted successfully."
			redirect_to user_topics_path(@topic.user) 
		else
			flash[:alert] = "There was a problem deleting your post."
			redirect_to :back
		end
	end

private
	
	def topic_params
		params.require(:topic).permit(:title, :body)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@topic = Topic.new
	end

	def search
		@users = User.where(email: params[:query])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "Your account was created sucessfully."
			redirect_to entry_path
		else
			flash[:alert] = "There was a problem signing you up."
			redirect_to :back
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.where(id: params[:id])
		if @user.update_attributes(user_params)
			flash[:notice] = "Your information was saved sucessfully."
			redirect_to user_path(@user.id)
		else
			flash[:alert] = "There was a problem updating your information."
			redirect_to :back
		end
	end

	def destroy
		@user = User.where(id: params[:id]).first
		if @user && @user.destroy
			session[:user_id] = nil
			flash[:notice] = "Your account was deleted successfully."
			redirect_to "/"
		else
			flash[:alert] = "There was a problem deleting your account."
			redirect_to :back
		end
	end

private

	def user_params
		params.require(:user).permit(:fname, :lname, :username, :email, :password)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		if session[:user_id]
			current_user ||=User.find(session[:user_id])
		end
	end
	
end

app/views/home/entry.html.erb
<br><br>
<img src="/Scan148.jpg", width="400px"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Forum</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div id="header">
			<h1>
				Forum
			</h1>
		</div>
		<div id="container">
			<div id="colone">
				<% if current_user %>
					<div id="navbar">
						<ul id="nav">
							<li>
								<%= link_to "Home", entry_path %>
							</li>
							<li>
								<%= link_to "Topics", topics_path %>
							</li>
							<li>
								<%= link_to "Users", users_path %>
							</li>
							<li>
								<%= link_to "Me", user_path(current_user.id) %>
							</li>
							<li>
								<%= link_to "Logout", logout_path, method: :delete %>
							</li>
						</ul>
					</div>
				<% end %>
			</div>
			<div id="coltwo">
				<% if flash[:notice] %>
					<%= flash[:notice] %>
				<% end %>
				<% if flash[:alert] %>
					<%= flash[:alert] %>
				<% end %>

				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/replies/index.html.erb
<h1>Replies Index</h1>

app/views/replies/new.html.erb
<h2>New reply</h2>
<div class="form">
	<%= form_for [@user, @topic, @reply] do |f| %>
		<%= f.label :body, "Content:" %>
		<br>
		<%= f.text_area :body %>
		<br>
		<%= f.submit "Reply", :class => "submit" %>
	<% end %>
</div>

app/views/topics/all.html.erb
<h2>All Topics</h2>

<div class="indent">
	<% @topics.each do |topic| %>
		<h4><%= link_to topic.title, user_topic_path(topic.user, topic.id) %></h4>
		<div class="indent">
			<span class="graytext">
			Author: <%= link_to topic.user.username, user_path(topic.user) %>
			<br>
			[posted <%=time_ago_in_words(topic.created_at) %> ago]</span>
		</div>
	<% end %>
</div>
<br>

<%=link_to "[Create a new topic]", new_user_topic_path(current_user.id), :class => "altlink" %>

app/views/topics/index.html.erb
<h2><%= link_to @user.username, user_path(@user.id), :class => "altlink" %>'s Topics</h2>
<div class="indent">
	<% if @user.topics.first %>
		<% @user.topics.each do |topic| %>
			<h4><%= link_to topic.title, user_topic_path(@user.id, topic.id) %></h4>
			<div class="indent">
				<span class="graytext">[posted <%=time_ago_in_words(topic.created_at) %> ago]
					<br>
					<% if @user == current_user %>
						<%= link_to "[Delete Post]", user_topic_path(@user.id, topic.id), method: :delete, confirm: "Are you sure you want to delete this post?" %>
					<% end %>
				</span>
			</div>
		<% end %>
	<% else %>
		<%= @user.username %> has not started any discussions yet.
	<% end %>
</div>

<% if @user == current_user %>
	<br><br>
	<h3>Create a New Topic...</h3>
		<div class="form">
			<%= form_for [@user, @topic] do |f| %>
				<%= f.label :title, "Title:" %>
				<br>
				<%= f.text_field :title %>
				<br>
				<%= f.label :body, "Content:" %>
				<br>
				<%= f.text_area :body %>
				<br>
				<%= f.submit "Post", :class => "submit" %>
			<% end %>
		</div>
<% end %>

app/views/topics/new.html.erb
<h2>New Topic</h2>
<div class="form">
	<%= form_for [@user, @topic] do |f| %>
		<%= f.label :title, "Title:" %>
		<br>
		<%= f.text_field :title %>
		<br>
		<%= f.label :body, "Content:" %>
		<br>
		<%= f.text_area :body %>
		<br>
		<%= f.submit "Post", :class => "submit" %>
	<% end %>
</div>

app/views/topics/show.html.erb
<h3><%= @topic.title %></h3>
<br>
<div class="authordiv">
	Author: <%= link_to @topic.user.username, user_path(@topic.user) %>
</div>
<% if @topic.body %>
<div class="replybody">
	<%= @topic.body %>
	<br><br>
	<div class="replytime">
		[posted <%=time_ago_in_words(@topic.created_at) %> ago]
	</div>
</div>
<% end %>
<div class="clear">
</div>
<% @topic.replies.each do |reply| %>
	<div class="replybody">
		<%= reply.body %>
		<br><br>
		<div class="replytime">
			[posted <%=time_ago_in_words(reply.created_at) %> ago]
		</div>
	</div>
	<div class="replydiv">
		<%= link_to reply.user.username, user_path(reply.user) %>
		<br>
		<% if reply.user == current_user %>
			<span class="graytext"><%= link_to "[Delete my Post]", user_topic_reply_path(current_user.id, @topic.id, reply.id), method: :delete, confirm: "Are you sure you want to delete your post?" %></span>
		<% end %>
	</div>
	<div class="clear">
	</div>
<% end %>

<br><br>

<h4>Reply...</h4>
<div class="form">
	<%= form_for [@user, @topic, @reply] do |f| %>
		<%= f.text_area :body %>
		<br>
		<%= f.submit "Reply", :class => "submit" %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit <%=user.username%>'s Information</h1>

app/views/users/index.html.erb
<h2>All Users</h2>

<div class="indent">
	<% @users.each do |user| %>
		<%= link_to user.username, user_path(user.id) %>
		<br><br>
	<% end %>
</div>

<%= link_to "[Search for User]", search_users_path, :class => "altlink" %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<div class="form">
	<%= form_for @user do |f| %>
		<%= f.label :fname, "First Name" %>
		<br>
		<%= f.text_field :fname %>
		<br>
		<%= f.label :lname, "Last Name" %>
		<br>
		<%= f.text_field :lname %>
		<br>
		<%= f.label :username %>
		<br>
		<%= f.text_field :username %>
		<br>
		<%= f.label :email %>
		<br>
		<%= f.text_field :email %>
		<br>
		<%= f.label :password %>
		<br>
		<%= f.password_field :password %>
		<br>
		<%= f.submit "Sign Up", :class => "submit" %>
	<% end %>
</div>

app/views/users/search.html.erb
<h2>Search for User</h2>

<div class="form">
	<%= form_tag "/search/users", method: "get" do %>
		<%= label_tag :query, "User Email:" %>
		<br>
		<%= text_field_tag :query %>
		<br>
		<%= submit_tag "Search", :class => "submit" %>
	<% end %>
</div>
<br>
<% if @users %>
	<h4>Results:</h4>
	<div class="indent">
		<% @users.all.each do |user| %>
			<%= link_to user.username, user_path(user.id) %>
			<br>
			<%= user.email %>
			<br><br>
		<% end %>
	</div>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %>'s Page</h2>

<%= link_to "[" + @user.username + "'s Topics]", user_topics_path(@user.id) %>

<% if @user == current_user %>
	<br><br>
	<h3>Create a New Topic...</h3>
		<div class="form">
			<%= form_for [@user, @topic] do |f| %>
				<%= f.label :title, "Title:" %>
				<br>
				<%= f.text_field :title %>
				<br>
				<%= f.label :body, "Content:" %>
				<br>
				<%= f.text_area :body %>
				<br>
				<%= f.submit "Post", :class => "submit" %>
			<% end %>
		</div>
	<br><br>
	<%= link_to "[Delete My Account]", user_path(current_user.id), method: :delete, confirm: "Are you sure you want to delete your account?" %>
<% end %>